<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Reference Include="ASCIISerializerManaged">
        <HintPath>..\Extras\ASCIISerializerManaged.dll</HintPath>
      </Reference>
      <Reference Include="BinarySerializerManaged">
        <HintPath>..\Extras\BinarySerializerManaged.dll</HintPath>
      </Reference>
      <Reference Include="CommonAPIManaged">
        <HintPath>..\Extras\CommonAPIManaged.dll</HintPath>
      </Reference>
      <Reference Include="Simulation.Common">
        <HintPath>..\..\Simulation\Binaries\Simulation.Common.dll</HintPath>
      </Reference>
      <Reference Include="Simulation.Data">
        <HintPath>..\..\Simulation\Binaries\Simulation.Data.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Common\Common.csproj" />
    </ItemGroup>

    <Target Name="PostBuild" AfterTargets="PostBuildEvent">
      <Exec Command="copy $(TargetDir)Simulation.Common.dll $(SolutionDir)..\Client\Assets\Libraries\Simulation.Common.dll&#xA;copy $(TargetDir)BeardedManStudios.dll $(SolutionDir)..\Client\Assets\Libraries\BeardedManStudios.dll&#xA;copy $(TargetDir)BinarySerializerManaged.dll $(SolutionDir)..\Client\Assets\Libraries\BinarySerializerManaged.dll&#xA;copy $(TargetDir)CommonManaged.dll $(SolutionDir)..\Client\Assets\Libraries\CommonManaged.dll&#xA;copy $(TargetDir)Networking.Common.dll $(SolutionDir)..\Client\Assets\Libraries\Networking.Common.dll&#xA;copy $(TargetPath) $(SolutionDir)..\Client\Assets\Libraries\$(TargetFileName)" />
    </Target>

</Project>
