<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <Reference Include="ASCIISerializerManaged">
        <HintPath>..\Extras\ASCIISerializerManaged.dll</HintPath>
      </Reference>
      <Reference Include="BinarySerializerManaged">
        <HintPath>..\Extras\BinarySerializerManaged.dll</HintPath>
      </Reference>
      <Reference Include="CommonManaged">
        <HintPath>..\Extras\CommonManaged.dll</HintPath>
      </Reference>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Common\Common.csproj" />
    </ItemGroup>

</Project>
