version: '3.8'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - "80:80"
    depends_on: 
      - sql-database
    networks:
      - back-gammon-network
    restart: always
  sql-database:
    image: mysql:latest
    container_name: TSQl-Database
    environment:
      MYSQL_ROOT_PASSWORD: ^YHN4rfv # Set a password for the root user
      MYSQL_DATABASE: backgammon
      #MYSQL_USER: root # Specify your custom MySQL username
      MYSQL_PASSWORD: !QAZ2wsx #Set a password for the custom user
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks: 
      -  back-gammon-network
networks:
  back-gammon-network: # Define the custom network